version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: highvol-db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: highvol_db
    ports:
      - "2010:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: highvol-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
